condition/condition.go
and default reason to "Error" if no specific reason is specified
=> Always set message on conditions

api/handler/validate.go, api/server.go, parse/builder/builder.go, types/server_types.go
Validate subtypes in create/update
=> Don't check for object in collection actions

api/writer/json.go, httperror/error.go, httperror/handler.go, parse/builder/builder.go, parse/parse.go, parse/read_input.go, types/convert/convert.go, types/convert/convert_test.go, types/server_types.go
APIContext constructor
status => Status
write writeOnly fields on create
=> fix json float parsing

controller/generic_controller.go, parse/builder/builder.go
Update rate limit on the controller
=> don't validate empty string as DNS name

condition/condition.go, signal/dump.go
Make conditions not modify as much
=> Move gorouting dump handler to norman

clientbase/common.go
Problem:
Running a server with a self signed cert will cause tls errors
Solution:
Add abillity to pass in a cert file to use for tls verification
=> Add option to pass in CACerts for verification

condition/condition.go, event/logger.go
Disable event logging for the moment
=> Only record forgetError if there is no message at all

clientbase/common.go, clientbase/ops.go
Add bearer auth support to clientbase, to support API v3 tokens.
=> Feat: Added token support to clientbase auth

api/handler/create.go, api/handler/delete.go, api/handler/list.go, api/handler/update.go, parse/parse.go, types/convert/convert.go, types/convert/transform.go
Return 404 when no store is configured (not 200)
Fix a series of url parsing issues
Transform helper method
=> If you hit /v3/projects/{ID}/schemas make sure schemas have correct URLs

store/schema/schema_store.go
add get to schemas that CanGet
=> 404 on schema not found

httperror/error.go, httperror/handler.go
Log underlying causes of APIErrors (if it is available).
Also, some general cleanup.
=> API error improvements

api/handler/list.go, controller/generic_controller.go, parse/parse.go, types/schemas.go
=> Allow types that start with cluster or project

generator/generator.go, generator/type_template.go
Problem:
Collections have actions but are not accessable through the types
clients
Solution:
Update template and generator to output actions living on collections
=> Add ability to generate collection actions

controller/generic_controller.go, generator/controller_template.go, generator/k8s_client_template.go, lifecycle/object.go, objectclient/object_client.go, types/reflection.go, urlbuilder/url.go
=> Move ObjectClient to different package

types/mapper/embed.go
https://github.com/rancher/rancher/issues/12588
=> Do not embed map if empty

authorization/all.go, types/server_types.go
Enables us to authorize actions and links
needed by https://github.com/rancher/rancher/pull/13093
=> Add CanDo function to AccessControl interface

generator/generator.go, generator/type_template.go
Problem:
Action generation code does not account for a resource action that does not
have an output
Solution:
Update template to output all actions
=> Update action generation code

leader/leader.go
=> Revert "Use a getID function instead of using hostname"

leader/leader.go
This reverts commit 807103dc58e0658672ae2d1ce363ed2c0d34af55.
=> Revert "Make leader election have leader callback"

generator/generator.go
Allows users to specify "backend" types that will have kubernetes
controllers and clients generated but no Rancher client generated.
The intended use to allow for creating a CRD and the supporting code
without having to expose the CRD in the Rancher API.
=> Support for backend types

api/handler/list.go, parse/collection.go, types/server_types.go
Problem:
Pagination is not showing up
Solution:
Pagination was being created properly but then dropped in favor of an
empty version. Save the pagination on the context so it can be accessed
later and not reset.
Issue: https://github.com/rancher/rancher/issues/13817
=> Fix pagination

api/writer/html.go
https://github.com/rancher/rancher/issues/13732
=> API-UI 1.1.5

parse/builder/builder.go, types/convert/convert.go
This reverts commit 5e344d90cd388c6b4de369899ec68c60d1dbe8cb.
Tested this and it broke more scenarios
=> Revert "Don't strip strings on output"

objectclient/object_client.go
=> Return proper v1.Status error, not masking marshaling error

store/proxy/proxy_store.go
This would cause a new watcher to be started without ever cleaning up the old one, which was causing memory leaks.
See: https://github.com/rancher/rancher/issues/15719
In my local cluster I just deployed the config specified [here](https://github.com/rancher/rancher/issues/15719#issuecomment-423062198) to my local cluster, and then opened up the default project in that cluster in the UI.
Without the fix, I see memory usage by the rancher process climb indefinitely at about 60Mb per minute. With the fix, the memory usage stays flat after the initial page load.
=> Ensure that closed watchers are always stopped

api/server.go, api/writer/html.go
Related issue https://github.com/rancher/rancher/issues/16252
=> [2.1]Dynamically response the JS and CSS of API UI

api/server.go, api/writer/html.go
Related issue: https://github.com/rancher/rancher/issues/15378 ,https://github.com/rancher/rancher/issues/16252
=> [2.2]Dynamically response the JS and CSS of API UI

types/reflection.go
Problem:
float type default value are convert to string now
Solution:
add default value for float
Issue:
https://github.com/rancher/rancher/issues/16958
=> Add default value to float type

api/writer/html.go
Problem:
Frame-Options header is not being set, this is a potential secutiry
issue
Solution:
Set the header "X-Frame-Options:deny"
=> Add Frame-Options header

httperror/error.go
Added function for checking if an error has code 404 (is not found).
=> Add IsNotFound error check

generator/controller_template.go, generator/lifecycle_template.go
Add PutClusterScoped to NewLifecycleAdapter & Remove PutClusterScoped from controllers
=> Global rolebindings garabage collection

controller/generic_controller.go
Mild code cleanup to reduce unnecessary variable shadowing.
No functional changes.
=> Fix error shadowing

pkg/remotedialer/types.go
Backport: https://github.com/rancher/remotedialer/pull/5
Backport Issue: https://github.com/rancher/rancher/issues/22947
=> Backport ping inc

store/proxy/proxy_store.go
https://github.com/rancher/rancher/issues/23198
=> show only err msg on watch

pkg/types/mapper/set_value.go
Port from mapper: https://github.com/rancher/mapper/pull/3
=> Dont allow entry to nil map

httperror/error.go
**Forwardport:** https://github.com/rancher/norman/pull/320
=> [Forwardport] 2.4: Add unauthorized error check

clientbase/common.go
This Pull Request introduces proxy support.
=> Proxy Support

controller/generic_controller.go, objectclient/object_client.go, pkg/subscribe/handler.go, store/proxy/proxy_store.go, types/reflection.go
https://github.com/rancher/rancher/issues/25965
Moving these to trace level makes debug more usable as most of these will be logged a lot.
=> Move debug log to trace

controller/generic_controller.go
Problem:
In a cluster with a large number of a single object, say 10k large
secrets, when the controller starts it attempts to list all of those
secrets and hits the client timeout
Solution:
Just increasing the client timeout does not work as the API server also
has a timeout. The API server ignores the limit when resourceVersion is
set to 0 which causes the call to take longer than either timeout
(running curl against the API server the call was taking over 3min on
average and pulling approx 2GB of data) so if resourceVersion is set to
0 reset it to empty string
=> Drop resourceVersion on lists when set to 0

store/proxy/proxy_store.go
**Original PR:**
https://github.com/rancher/norman/pull/370
**Issue:**
https://github.com/rancher/rancher/issues/27505
=> [Backport] 2.4: Proxy store context 2.4

go.mod, store/proxy/proxy_store.go
This logging should help narrow down where time is being spent when doing list calls and a performance issue is being seen.
=> Add trace logging to List

pkg/kwrapper/k8s/k3s_linux.go
https://github.com/rancher/rancher/issues/28279
=> k3s disable agent removal

types/mapper/selflink.go
https://github.com/rancher/rancher/issues/31367
=> Fix self link

types/mapper/selflink.go
https://github.com/rancher/rancher/issues/31467
=> Use lower name

generator/funcs.go, generator/generator.go, generator/k8s_client_template.go, go.mod, go.sum
**Issue**:
https://github.com/rancher/rancher/issues/37360
=> Only update change v2.5

.drone.yml
Closes: https://github.com/rancherlabs/eio/issues/1168
=> EIO-1168: Ignore FOSSA failures

generator/k8s_client_template.go
User lasso's configure useragent functionality.
**Issue:**
https://github.com/rancher/rancher/issues/38775
=> Add ability to copy controller and add useragent

generator/k8s_client_template.go
**Issue:**
https://github.com/rancher/rancher/issues/40021
**Original PR:**
https://github.com/rancher/norman/pull/423
=> [Forwardport] v2.7: Add ability to copy controller and add useragent

.github/renovate.json, .github/workflows/release.yaml, README.md, VERSION.md
=> Create release on tag push

.github/workflows/release.yaml
=> [v0.4] Create release on tag push

.github/workflows/release.yaml, Dockerfile.dapper
Had to add gawk because the CI was failing with `awk` not being found when installing golang ci...
=> [v0.2] Create release on tag push

.github/workflows/release.yaml, Dockerfile.dapper
Had to add gawk because the CI was failing with `awk` not being found when installing golang ci...
=> [v0.1] Create release on tag push

Dockerfile.dapper, api/access/list.go, go.mod, parse/parse.go
Issue: https://github.com/rancher/rancher/issues/47764
=> [main] Upgrade go version to 1.23

Dockerfile.dapper, api/access/list.go, go.mod, parse/parse.go
Backport from #586 
Issue: https://github.com/rancher/rancher/issues/47764
=> [release/v0.4] Upgrade go version to 1.23

Dockerfile.dapper, api/access/list.go, go.mod, parse/parse.go
backport from #586 
issue: https://github.com/rancher/rancher/issues/47764
=> [release/v0.3] Upgrade go version to 1.23

go.mod, go.sum
Ref [#52095](https://github.com/rancher/rancher/issues/52095)
=> Bump to wrangler v3.3.0-rc.2
