lifecycle/object.go

Now the we are properly formatting finalizer names, they can
successfully be added to namespaces. This has is no longer needed.

Allow namespaces to have finalizers

---

controller/cluster_check.go
generator/controller_template.go
generator/lifecycle_template.go
lifecycle/object.go

Some worload controllers need to watch resoruces in the mangement plane
and react to them. But, they should only react to resources that
correspond to their cluster. This adds framework support for that.

Add suport for cluster scoped controllers

---

parse/parse.go

When parsing URL paths, unescape them so that characters that needed escaped
in order to be placed in the a path segment are returned to their original
form.

Fix url escaping

---

httperror/error.go

Add an IsConflict function to httperror package.  The purpose of this
change is to allow the testing of APIErrors in a controlled and
centralized way.
Supports functionality in issue:
https://github.com/rancher/rancher/issues/11378
Dependency of:
https://github.com/rancher/rancher/pull/12010

Add IsConflict to httperror

---

httperror/handler/handler.go

If a url has special characters in it (especially %), logrus is
messing it up and printing %!F(MISSING) or similar.

make url error logging prettier

---

clientbase/ops.go

Problem:
doAction assumes that an action would have a response body which causes
JSON unmarshal errors
Solution:
Only attempt to Unmarshal when a response is expected

Update doAction to not expect a response

---

api/handler/query.go
store/wrapper/wrapper.go
types/condition.go
types/server_types.go

This change gives norman the ability to filter api requests based on the
default value of fields.  Before, it would filter on the actual data in
the resource, and then apply default values to the resource before
returning.
Issue:
rancher/rancher#13418

Filter on defaults

---

types/reflection.go

This change adds an early panic if the type of the obj supplied to the
`MustImport` func is a pointer.  This is to prevent a later, cryptic,
error that is not as clear to diagnose.

Adding error if not a pointer

---

generator/generator.go
parse/builder/builder.go
types/reflection.go

1. Use IsDNS1123Label instead of IsDNS1123Subdomain for `dnsLabel.
2. Add `hostname` tag and use IsDNS1123Subdomain for validation.
Related issues:
https://github.com/rancher/rancher/issues/13516

Add hostname tag and fix dnsLabel validation issue

---

types/mapper/embed.go

Need to let embed.go mapper to insert a nil value for a field if mentioned in the schema. 
Usecase for this: In cases where an Update on the resource will be removing some field, we need to update the existing k8s resource's field by setting its  value to explicit nil.
https://github.com/rancher/rancher/issues/13584
@alena1108 review pls

Changes to Mapper embed to insert nil value if applicable for a schema field

---

generator/generator.go
parse/builder/builder.go

k8s uses restricted format for services
dnsLabelRestricted: dns1035LabelFmt string = "[a-z]([-a-z0-9]*[a-z0-9])?"
dnsLabel:dns1123LabelFmt string = "[a-z0-9]([-a-z0-9]*[a-z0-9])?"
https://github.com/rancher/rancher/issues/13498
@ibuildthecloud just wanted to make sure you are ok with the name; didn't want to use explicit 1035 in the name

DnsLabelRestricted type to validate against RFC 1035

---

controller/generic_controller.go

This changes the framework from using glog to using logrus, which is
what the rest of code uses.

Use logrus to log errors and panics

---

controller/generic_controller.go
controller/noop_metrics.go

With the built in prom. metrics provider, the k8s machinery doesnt
deregister metrics when controllers are removed. So over time as
things like clusters are created or removed the metrics are not
cleaned up. The metrics types for the cache and queue are also
very large. They can take ~1GB of RAM in a 100 cluster setup.
Also, Rancher is not exposing these stats so they are unobservable.

Default to noop metric provider

---

store/proxy/proxy_store.go

To test, I used
```
cluster = admin_cc.cluster
count = 0
for i in range(0,50):
print(i)
time.sleep(10)
try:
curr = cluster.data_dict()['enableNetworkPolicy']
upd = not curr
cluster = admin_cc.management.client.update(cluster,id='c-7cnlz',name='custom',
rancherKubernetesEngineConfig=cluster.data_dict()['rancherKubernetesEngineConfig'],
enableNetworkPolicy=upd)
assert cluster.data_dict()['enableNetworkPolicy'] == upd
except ApiError as e:
assert e.value.error.status != 409
count = count + 1
assert count == 0
``` 
https://github.com/rancher/rancher/issues/14940

return on first try if err is not conflict

---

types/schemas.go

Fixing bug in Norman where references to a schema were improperly deleted.
This is to support pluggable container drivers.
Issue:
https://github.com/rancher/rancher/issues/12698

Pluggable Drivers

---

condition/condition.go
condition/condition_test.go

add a method to check if the error message contains a tmp file path. It
is to prevent updating resource's condition forever and causing the
controller flapping. https://github.com/rancher/rancher/issues/15103

add method to compare if error has tmp file path

---

controller/generic_controller.go

https://github.com/rancher/rancher/issues/13049
@ibuildthecloud do you see any problem with reducing the log level for this particular type of error?

Log forget error in debug

---

parse/builder/builder.go
types/convert/convert.go

This change is in support of the CA linefeed fix.  Reverts a reverted commit so whitespace are not automatically stripped on lists.
Issue:
https://github.com/rancher/rancher/issues/13831
This reverts commit 4bcc025ae37faa5f4a8a6614df4e8133530f84d2.

Revert "Revert "Don't strip strings on output""

---

types/schemas.go
types/types.go

This change adds a dynamic field indicator to the field struct.  This is so
we can remove the dynamic fields from an existing schema before merging the
dynamic schema and actual schema to prevent removed dynamic fields form being
incorrectly left behind on the schema.
Issue:
https://github.com/rancher/rancher/issues/12698

Add dynamic field to field struct

---

condition/condition.go
controller/error.go

Norman Condition automatically generate condition information based on
the error the handler would return in Condition.Do function.
handler function usually return 2 types of error. the error can be
ignored and the error can not be ignored.
According to current implementation, Condition.Do function generate
condition with error state even if handler return error can be ignored.
The error that can be ignored should be ignored in the context of
condition as well.
So this commit introduce new field which is Reason to ForgetError so
that the developer can put special reason other than Error when
ForgetError is expected to happen by expected procedure like
provisioning and wait for something and Norman Condintion respect to
this field when try to generate condition information based on error …

Allow to put Reason in controller.ForgetError

---

controller/generic_controller.go

There are usecases to enable only queue metrics for monitoring purpose, but currently norman only provide a option to turn on/off queue, reflector metrics together. 
So this PR provide more precise control for controller related metrics so that user can turn on only queue metrics.

Enable fine-grained control for Controller related metrics

---

parse/builder/builder.go
types/convert/convert.go

As https://github.com/rancher/api-spec/blob/master/specification.md#schema-fields, we should support float type in Rancher API. The metrics type of monitoring has a value field that should be float type.
Related issue: https://github.com/rancher/rancher/issues/14230

Add float support for Rancher API

---

store/proxy/proxy_store.go

Some cloud provider k8s APIs have random timeouts on listing and getting.
This change introduces a retry on lists and gets

List and Get retry logic

---

api/server.go

The defaul http server logs panics to the server's log handler.
That goes to debug level and thus panics are not seen when running
rancher at a normal log level.
This fixes the problem by catching the panic at the top level norman
http handler and logging them as errors there.

Log panics as error

---

objectclient/object_client.go

Problem:
If you set a resource's labels to a global/shared map variable,
norman will modify that map by adding a label. In race conditions,
this can cause a concurrent map read/write panic.
Solution:
Copy the map in norman before modifying it.
https://github.com/rancher/rancher/issues/18036

Fix concurrent map read/write

---

types/schemas.go
types/types.go

This change makes it so that schemas can be replaced when they already exist.
This is to support the ability for kontainer drivers to update their dynamic
schemas.
Issue:
https://github.com/rancher/rancher/issues/17712

Adding ability to replace schemas

---

pkg/remotedialer/client_dialer.go
restwatch/rest.go
store/proxy/proxy_store.go

This change addresses an issue where AKS clusters would timeout due to Azure
lbs failing to send tcpResets (RST) after an idle timeout. This causes errors
to appear on the Rancher UI and logs. This issue resolves that by adding a
keep alive to the dialer and changing some timeouts to prevent the errors from
appearing.
This is only for AKS cluster provisioned through the AKS Kontainer Driver
integration, imported clusters still exhibit this behavior.
Issue:
https://github.com/rancher/rancher/issues/14354

Adding code to address aks timeout issue

---

clientbase/common.go

In the old code, `resp` defined at line 215 will be rewrite at line 241. So that the `resp` after `defer` at both line 219 and 245 will operate the same one. And the other one leaks.

ensure resp.Body closed

---

clientbase/ops.go

Other methods such as `DoCreate` handle nil `createObj` and `respObject` by initializing the variables. `DoModify` contains no such checks.
Rancher Terraform provider ignores the response and passes nil, which then crashes with `json: Unmarshal(nil)` https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_auth_config_adfs.go#L244
This issue manifested here https://github.com/rancher/terraform-provider-rancher2/issues/59

Fix DoModify crashing on nil objects

---

parse/collection.go

Problem:
Response times are too slow for resources such as pods. The UI is making paged requests. Since response are paginated after processing, each paged response takes about the same amount of time for the backend to process as a full response. Pagination is not being used to fragment results and -1 is being passed as a parameter by the UI.
Solution:
There is now a recognized option for opting out of pagination. Now, a value of -1 will prevent the response from being paginated.
Issue:
https://github.com/rancher/rancher/issues/18870
https://github.com/rancher/rancher/issues/18522
https://github.com/rancher/rancher/issues/18295

Add no pagination option

---

store/proxy/proxy_store.go
types/server_types.go

Problem:
Requests associated with a particular project are not being filtered. Consequently, requests for projects that posses a fraction of total resources are taking longer than necessary to return.
Solution:
Norman now tracks and assigns project namespaces which are necessary for rancher to filter project requests.
Issues:
https://github.com/rancher/rancher/issues/18870
https://github.com/rancher/rancher/issues/18522
https://github.com/rancher/rancher/issues/18295
https://github.com/rancher/rancher/issues/16605

Track namespaces in options property

---

generator/controller_template.go
generator/scheme_template.go

Fix apimachinery work on list objects
https://github.com/kubernetes/apimachinery/blob/ef51ab160544f9d05b68e132a4af0b0fab459954/pkg/runtime/conversion.go#L46:6

Fix listing

---

store/wrapper/wrapper.go
store/wrapper/wrapper_test.go

Address issue: https://github.com/rancher/rancher/issues/15128
Problem:
Pagination is broken when the schema store is wrapped twice
Solution:
Do not wrap a wrapped schema store

Do not wrap a wrapped schema store

---

generator/controller_template.go
parse/parse.go
store/schema/schema_store.go
types/types.go

Related feature
Add feature flags
Rancher PR:
https://github.com/rancher/rancher/pull/20593

Add enable function to schema and addFeature functions

---

clientbase/common.go
pkg/remotedialer/client.go
pkg/remotedialer/peer.go

To prevent agent from being hung in the middle of Websocket Session
Handshake, We'd better to set HandshakeTimeout
Related to https://github.com/rancher/rancher/issues/21117

Configure HandshakeTimeout in websocket.Dialer

---

store/proxy/proxy_store.go
store/proxy/proxy_store_test.go

Address issue: https://github.com/rancher/rancher/issues/17823
Problem:
There is no way to pass gracePeriodSeconds for force deletion
Solution:
Get deletion options in query params and pass it in proxy store
More Infos:
1. In this solution, The APIs do force deletion by passing `gracePeriodSeconds=0`, which is the same way as apiserver. 
1. Kubernetes apiserver accepts delete options from entity-body of DELETE requests before v1.4, and support both query params and entity-body since v1.4. Because the usage of request body in DELETE request is kinda discouraged in HTTP/1.1 semantics and not supported by some clients. However, kubectl still pass deletion options to apiserver using request body. Refer to [this issue](https://github.com/kubernetes/kubernetes/issues/34856) for details.
2. This …

Pass delete options in proxy store

---

pkg/types/reflection.go

See: https://github.com/kubernetes-sigs/controller-tools/pull/138
Avoiding just checking on `duration` because that could be `time.duration` which is not a string.

Switch duration to string to handle k8s metav1.duration

---

generator/controller_template.go
objectclient/object_client.go

This PR will introduces ListNamespaced method for ObjectClient, that help to do namespaces list requests.
Related issue: https://github.com/rancher/rancher/issues/23934

Add ListNamespaced method for ObjectClient

---

store/proxy/proxy_store.go

changing error level to debug, the error is already handled, new watcher gets started after the current one is closed. Closing is not done by rancher, it's a k8s behavior.
https://github.com/rancher/rancher/issues/23957

change loglevel for watcher err

---

store/proxy/proxy_store.go

changing error level to debug, the error is already handled, new watcher
gets started after the current one is closed. Closing is not done by
rancher, it's a k8s behavior.

backport debug level pr

---

controller/generic_controller.go

A leak would occur if either a GenericController was created
and Sync() or Start() was never called or if Sync() failed.

Fix goroutine leak on failed sync() or before

---

controller/generic_controller.go

A leak would occur if either a GenericController was created
and Sync() or Start() was never called or if Sync() failed.
https://github.com/rancher/norman/pull/324

cherry-pick Fix goroutine leak on failed sync() or before 

---

store/crd/init.go

This PR fixes concurrent CRD creation.
Multiple Rancher replicas concurrently create CRDs. According to implementation, empty CRD struct will be used if CRD already exists, which cause Rancher panic (but succeed on next pod restart when all CRDs already created).
Empty structure generated in https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go#L108
Original CRD struct should be used if AlreadyExists https://github.com/rancher/norman/blob/master/store/crd/init.go#L199
Panic happens here https://github.com/rancher/norman/blob/master/store/crd/init.go#L65 because of usage of empty CRD structure with uninitialized fields (crd.Name)
It doesn't break the whole deployment, but increase deployment …

Use original crd if already exists

---

pkg/kwrapper/k8s/k3s_linux.go

**Problem**
Registration [options](https://rancher.com/docs/k3s/latest/en/installation/install-options/) have been update with the more recent k3s versions 
**Solution**
Update `--storage-endpoint` and `--storage-backend` to`--datastore-endpoint` 
https://rancher.com/docs/k3s/latest/en/installation/datastore/#datastore-endpoint-format-and-functionality
**Issue**
https://github.com/rancher/rancher/issues/24439

k3s options update

---

generator/type_template.go

This PR adds `func (c *{{.schema.CodeName}}Client) ListAll(opts *types.ListOpts)` on types_template.go. `ListAll` function will depaginate API answer results, appending them into returned collection.
Related to https://github.com/rancher/telemetry/pull/40

Added ListAll function on types_template.go to depaginate results on collection

---

api/validate.go

- Only set the cookie if it doesn't exist instead of on every request
- Always mark it secure (it was previously getting re-sent, as not-secure if it did exist, on every request)
- Check the value against the header even if there was no value, so that
a request that is missing the cookie fails (even though this should never come up in a situation where you're logged in).

CSRF Cookie fixes

---

api/validate.go

- Only set the cookie if it doesn't exist
- Always mark it secure (it was previously getting re-sent as not)
-.Check the value against the header even if there was no value (so that
a request that is missing the cookie but should have had one fails).

[backport] CSRF Cookie fixes

---

controller/cluster_check.go

Problem:
cluster_check relies on reflect which is slow and causes a large
performance hit which is especially noticable on restart
Solution:
Add a new interface ObjectClusterName that objects can implement so
reflect isn't used for that type

Update cluster_check to use interface if available

---

store/proxy/proxy_store.go

**Problem:**
Using the requests context may cause the watch to end too early
**Solution:**
Use store's context
**Issue:**
https://github.com/rancher/rancher/issues/27505

Change context in realWatch

---

parse/builder/builder.go

Prior, empty array were converted to nil. In some cases the
difference between a nil and empty array are not arbitrary.
Now, empty arrays will be converted to empty interface arrays
and nil array will be converted to nil interface arrays.

Differentiate between empty and nil arrays

---

pkg/kwrapper/k8s/k3s_linux.go

Without this the pods inside the rancher run k3s cluster have no DNS server and fail to query any external DNS. 
Issue: https://github.com/rancher/rancher/issues/28279

Enable coredns in k3s

---

types/mapper/object.go
types/mapper/selflink.go

https://github.com/rancher/rancher/issues/31367

Add self link mapper

---

generator/generator.go
parse/builder/builder.go

Currently, *string fields in Go structs are converted to {type:
string, nullable: true} in the API schema, which is right, but then
converted down to just `string` when converted to generated client
structs. Without this patch, there is no way to express that *strings
should stay as *strings when run through the generator, because the
'nullable' flag is ignored. Compare this to *bools, which become
`boolean` in the schema and then correctly converted back to *bool in
the generator. This patch adds a backwards-compatible way to opt in to
converting *strings in the original struct to *strings in the generated
struct.
https://github.com/rancher/rancher/issues/30480
https://github.com/rancher/rancher/issues/32440

Add 'nullablestring' field type

---

store/proxy/proxy_store.go

Rancher auth filter is now adding "Impersonate-Extra-" info headers that carry user's info from external identity provider, so we need to pass through those headers so that the info gets logged to k8s audit log.
Rancher PR: https://github.com/rancher/rancher/pull/31711
https://github.com/rancher/rancher/issues/31166

Adding impersonate-extra headers to request

---

pkg/kwrapper/k8s/k3s_linux.go

This changes embbed k3s server log from os.stdout to file. K8s api-server log is quiet noisy and impact the ability to read rancher server log if combined together. 
https://github.com/rancher/rancher/issues/31859

Log k3s server logs to file

---

store/crd/init.go

Replaced CRD API from `v1beta1` to `v1` to support k8s v1.22.
Note that apiextensions.k8s.io/v1 for CRD is supported from k8s v1.16 making it OK to do straight change as Rancher v2.6 release to support k8s 1.18+.

Updated to use v1 API for CustomResourceDefinition

---

generator/generator.go

When generating types, any field with name "id" was being skipped. The intention
here was to skip the "id" field of the embedded types.Resource struct. A type
will have an embedded types.Resource struct when the hasGet function returns
true. Therefore, this hasGet function is also used to skip the id fields as
desired.

Stop ignoring id fields for sub-schemas

---

store/proxy/proxy_store.go

refer to: https://github.com/rancher/rancher/issues/32847
There is no default converter for `DeleteOptions` in the latest(1.19+) SDK, we can use `Convert_url_Values_To_v1_DeleteOptions`.
https://github.com/kubernetes/kubernetes/issues/94688
If this can be merged, feel free to backport to v2.5.

Fix DeleteOption encoding errors for norman api

---

types/schemas.go

We sometimes faced the panic `fatal error: concurrent map read and map write` or `fatal error: concurrent map iteration and map write`.
we found the current lock is not enough:
```
schemas, ok := s.schemasByPath[path]
```
this line seems wanted to copy but it's not copy because it's map.
and then, we have the possibility to face a panic like below
`concurrent map read and map write` :
```
schema := schemas[name]
```
`concurrent map iteration and map write` :
```
for _, check := range schemas {
```
This PR fixes the above issue by extending lock to the end of this function.

Fix doSchema lock issue

---

generator/controller_template.go

Deprecated comments should begin with `"Deprecated:"` so it is recognized by modern linters.
https://github.com/golang/go/wiki/Deprecated

Update Deprecated comment in controller template

---

Dockerfile.dapper
api/writer/html.go
api/writer/json.go
clientbase/ops.go
condition/condition.go
controller/cluster_check.go
controller/generic_controller.go
example/main.go
generator/generator.go
parse/parse.go
parse/read_input.go
pkg/dump/dump.go
pkg/subscribe/handler.go
scripts/validate
store/proxy/proxy_store.go
types/encoder.go
types/mapper/move.go

Migrated to a SUSE container, a newer version of Go, and using golangci-lint for all linting. Fulfills https://github.com/rancher/tasks/issues/203

Updated dapper files

---

store/crd/init.go

related issue: https://github.com/rancher/rancher/issues/41840
to fix linting error: 
```
store/crd/init.go:138:9: SA1019: wait.Poll is deprecated: This method does not return errors from context, use PollWithContextTimeout. Note that the new method will no longer return ErrWaitTimeout and instead return errors defined by the context package. Will be removed in a future release. (staticcheck)
return wait.Poll(500*time.Millisecond, 60*time.Second, func() (bool, error) {
^
```

replace deprecated wait.Poll with wait.PollUntilContextTimeout

---

.drone.yml
scripts/ci

The test script is not running in the `ci` script. 
The changes:
- Run the test script in the ci script
- Move dapper image to `v0.6.0` as that is the latest image (2 years old). The 1.11.2 version is 7 years old [according to docker hub](https://hub.docker.com/r/rancher/dapper/tags?page=1&name=1.11.2).
I have dropped the following changes:
- The git command added allows users on linux to run dapper with DAPPER_MODE=bind which makes builds a bit faster by not requiring the repository to be copied, a bind mount can be used instead.
- I'm not sure that's the proper way to fix this, need more investigation from me.
- Add volumes for caching go modules. This also makes the build faster.
- This caching might work differently on GHA so instead of making it work both here and later, I'll defer …

Run go test in CI

---

.drone.yml
scripts/ci

The test script is not running in the `ci` script. 
The changes:
- Run the test script in the ci script
- Move dapper image to `v0.6.0` as that is the latest image (2 years old). The 1.11.2 version is 7 years old [according to docker hub](https://hub.docker.com/r/rancher/dapper/tags?page=1&name=1.11.2).

[v2.7] Run go test in CI

---

types/schemas.go
types/schemas_test.go

We neglect to remove schemas from s.schemas in s.doRemoveSchema which results in duplicate entries in s.schemas which are never removed. This introduces a memory leak of ~300 mb a week on a large rancher cluster.
https://github.com/rancher/rancher/issues/47694

remove s.schemas in doRemoveSchema

---

types/schemas.go
types/schemas_test.go

We neglect to remove schemas from `s.schemas` in `s.doRemoveSchema` which results in duplicate entries in `s.schemas` which are never removed. This introduces a memory leak of ~300 mb a week on a large rancher cluster.
https://github.com/rancher/rancher/issues/47694

Schema leak

---

types/schemas.go
types/schemas_test.go

backport https://github.com/rancher/norman/pull/523
> We neglect to remove schemas from s.schemas in s.doRemoveSchema which results in duplicate entries in s.schemas which are never removed. This introduces a memory leak of ~300 mb a week on a large rancher cluster.
> 
> https://github.com/rancher/rancher/issues/47694

[v0.4] Fix schemas leak

---

types/schemas.go
types/schemas_test.go

backport https://github.com/rancher/norman/pull/523
> We neglect to remove schemas from s.schemas in s.doRemoveSchema which results in duplicate entries in s.schemas which are never removed. This introduces a memory leak of ~300 mb a week on a large rancher cluster.
>
> https://github.com/rancher/rancher/issues/47694

[v0.3] Backport memory leak
